# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ricardo Arredondo
email: ricardo.richo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Init blog.
  An evolving blog, currently using jekyll-org.
domain: ricardoricho.github.io
url: "https://ricardoricho.github.io"
baseurl: "ricardoricho.github.io"
twitter_username: _richo
github_username:  ricardoricho

# Theme settings

collections:
  init-blog:
    title: Init-blog # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post


navigation_header:
  - title: Home
    url: /
  - title: Resume
    url: /resume/

navigation_footer:
  - title: Home
    url: /
  - title: About
    url: /about/

social_links:
  GitHub: https://github.com/ricardoricho
  LinkedIn: https://linkedin.com/in/ricardo-arredondo

sharing_links:
  LinkedIn: true
  GitHub: true

# Build settings

theme: alembic-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-org
