#+layout: post
#+title: Welcome to Jekyll-org!
#+date: 2026-03-30 00:12:32 +0000
#+categories: Jekyll init

This is the first post, just to see how things work.

You’ll find this post in your ~_posts~ directory. Go ahead and edit it and
re-build the site to see your changes. You can rebuild the site in many
different ways, but the most common way is to run ~jekyll serve~, which launches
a web server and auto-regenerates your site when a file is updated.

Jekyll-org requires blog post files to be named according to the following format:

~YEAR-MONTH-DAY-title.MARKUP~

Where ~YEAR~ is a four-digit number, ~MONTH~ and ~DAY~ are both two-digit
numbers, and ~MARKUP~ is the file extension representing the format used in the
file. Jekyll-org support org files. After that, include the necessary front
matter. Take a look at the source for this post to get an idea about how it
works.

Jekyll also offers powerful support for code snippets in org files using
~#+begin_src~ block:

#+begin_src ruby
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
#+end_src

Check out the [[https://jekyllrb.com/docs/home][Jekyll docs]] for more info on how to get the most out of
Jekyll. File all bugs/feature requests at [[https://github.com/jekyll/jekyll][Jekyll’s GitHub repo]] or [[https://github.com/ricardoricho/jekyll-org][Jekyll-org's
GitHub repo]] if are related to org files. If you have questions, you can ask them
on [[https://talk.jekyllrb.com/][Jekyll Talk]].
